version: '3.9'

services:
  bookservice:
    build:
      context: ./Services/BookService
    container_name: bookservice
    ports:
      - "5003:80"
    depends_on:
      - sqlserver

  apigateway:
    build:
      context: ./Gateway/ApiGateway
    container_name: apigateway
    ports:
      - "5000:80"
    depends_on:
      - bookservice
