version: '3.9'

services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "P@ssw0rd!"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver-data:/var/opt/mssql

  bookservice:
    build:
      context: ./Services/BookService
    container_name: bookservice
    ports:
      - "5003:80"
    depends_on:
      - sqlserver

  apigateway:
    build:
      context: ./Gateway/ApiGateway
    container_name: apigateway
    ports:
      - "5000:80"
    depends_on:
      - bookservice

volumes:
  mongo-data:
  sqlserver-data:
